name: Push Image to DockerHub
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: 'MLFlow version'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: set version number
        id: set-version
        run: |
          echo "::set-output name=version::$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")"
      - name: Build, tag, and push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            mlflow_version:${{ github.event.inputs.version || steps.set-version.outputs.version }}
          tags: muttdataai/mlflow:${{ github.event.inputs.version || steps.set-version.outputs.version }}
